mensajeria:
  driver: postgresql
  host: localhost
  port: 5432
  user: postgres
  password: root
  db: mensajeria

bodega:
  driver: postgresql+psycopg2
  host: proyectobodega.postgres.database.azure.com
  port: 5432
  user: adminbodega
  password: Goddess9039
  db: proyectobodega



# mensajeria:
#   driver: postgresql
#   port: 5432
#   user: postgres
#   db: mensajeria
#   password: root
#   host: localhost

# bodega:
#   driver: postgresql+psycopg2
#   host: proyectobodega.postgres.database.azure.com
#   port: 5432
#   user: adminbodega
#   password: Goddess9039#
#   db: proyectobodega

# mensajeria:
#   driver: postgresql
#   port: 5432
#   user: postgres
#   db: mensajeria
#   password: root
#   host: localhost

# bodega:
#   driver: postgresql
#   port: 5432
#   user: adminbodega
#   db: proyectobodega
#   password: Goddess9039#
#   host: proyectobodega.postgres.database.azure.com