CO_SA:
  drivername: postgresql
  user: postgres
  password: 123456
  host: localhost
  port: 5432
  dbname: mensajeria_bd

ETL_PRO:
  drivername: postgresql
  user: postgres
  password: 123456
  host: localhost
  port: 5432
  dbname: bodega_mensajeria